---
config:
  keypair_name: "aws-eb2"
  private_key_path: "~/.ssh/aws-eb2"
  ami: "ami-405f7226"
  region: "eu-west-1"

  master_instance_type: "t2.micro"
  minion_etl_instance_type: "t2.small"
  minion_website_instance_type: "t2.nano"

  master_security_group: 'vagrant'
  minion_website_security_group: "vagrant-website"
  minion_etl_security_group: "vagrant-website"

  master_elastic_ip: "34.250.91.247"
  minion_website_elastic_ip: "34.251.111.102"
  minion_etl_elastic_ip: "34.251.173.101"
